<a href="https://colab.research.google.com/github/talktoarusharya/LSTM_next_word/blob/main/LSTM_text_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [253]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import string
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [254]:
df = pd.read_csv('/content/qoute_dataset.csv')

In [255]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [256]:
sentences = df['quote'].head(100);
sentences.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [257]:
tokenizer = Tokenizer()

In [258]:
tokenizer.fit_on_texts(sentences)

In [259]:
tokenizer.word_index

{'”': 1,
 'you': 2,
 'to': 3,
 'is': 4,
 'the': 5,
 'a': 6,
 'of': 7,
 'and': 8,
 'it': 9,
 'i': 10,
 'not': 11,
 'be': 12,
 'that': 13,
 'in': 14,
 'but': 15,
 'love': 16,
 'can': 17,
 'your': 18,
 'who': 19,
 'will': 20,
 'have': 21,
 'are': 22,
 'what': 23,
 'as': 24,
 'one': 25,
 'up': 26,
 'all': 27,
 'if': 28,
 'for': 29,
 'with': 30,
 'my': 31,
 '“the': 32,
 'or': 33,
 'never': 34,
 'no': 35,
 'more': 36,
 '“i': 37,
 'her': 38,
 'she': 39,
 'think': 40,
 "it's": 41,
 'make': 42,
 'so': 43,
 'when': 44,
 'than': 45,
 'only': 46,
 'like': 47,
 'because': 48,
 'from': 49,
 'do': 50,
 'we': 51,
 '“it': 52,
 'life': 53,
 "don't": 54,
 'them': 55,
 'me': 56,
 'live': 57,
 'good': 58,
 'just': 59,
 '“a': 60,
 'know': 61,
 'day': 62,
 'going': 63,
 'give': 64,
 'at': 65,
 'keep': 66,
 '“if': 67,
 '“you': 68,
 'may': 69,
 'people': 70,
 'time': 71,
 'book': 72,
 'see': 73,
 'world': 74,
 'our': 75,
 'without': 76,
 'has': 77,
 'how': 78,
 'truth': 79,
 'friends': 80,
 'go': 81,
 'on': 82,
 'read': 83,
 'an': 84,
 '“there': 85,
 'everything': 86,
 'must': 87,
 'man': 88,
 'get': 89,
 'some': 90,
 'come': 91,
 'let': 92,
 'much': 93,
 "doesn't": 94,
 'believe': 95,
 'yourself': 96,
 'thing': 97,
 'about': 98,
 'great': 99,
 'every': 100,
 'there': 101,
 'us': 102,
 'way': 103,
 'by': 104,
 'things': 105,
 'lives': 106,
 'really': 107,
 'am': 108,
 'thinking': 109,
 'nothing': 110,
 'person': 111,
 'become': 112,
 "you're": 113,
 'remember': 114,
 'best': 115,
 'well': 116,
 'too': 117,
 "you'll": 118,
 'find': 119,
 'makes': 120,
 'always': 121,
 'else': 122,
 'hurt': 123,
 'opposite': 124,
 'indifference': 125,
 'happens': 126,
 'which': 127,
 'want': 128,
 'something': 129,
 'music': 130,
 'everyone': 131,
 'reading': 132,
 'drink': 133,
 'die': 134,
 'harry': 135,
 'though': 136,
 'other': 137,
 'genius': 138,
 'better': 139,
 'until': 140,
 'hate': 141,
 'most': 142,
 'heart': 143,
 'fail': 144,
 'trying': 145,
 'then': 146,
 'high': 147,
 'old': 148,
 'understand': 149,
 'before': 150,
 'now': 151,
 'where': 152,
 'death': 153,
 'books': 154,
 'this': 155,
 '“life': 156,
 'any': 157,
 'fairy': 158,
 'tales': 159,
 'should': 160,
 'small': 161,
 '“to': 162,
 'mind': 163,
 'little': 164,
 'kind': 165,
 'enough': 166,
 'anything': 167,
 'those': 168,
 'big': 169,
 'its': 170,
 'forget': 171,
 'was': 172,
 'right': 173,
 'done': 174,
 'could': 175,
 'troubles': 176,
 "i'm": 177,
 'truly': 178,
 'two': 179,
 'ways': 180,
 'miracle': 181,
 'stupid': 182,
 'absolutely': 183,
 'loved': 184,
 "i've": 185,
 'woman': 186,
 'tea': 187,
 'matter': 188,
 'mess': 189,
 'part': 190,
 "they'll": 191,
 'ones': 192,
 'through': 193,
 'true': 194,
 'also': 195,
 'say': 196,
 "can't": 197,
 'half': 198,
 'mean': 199,
 'hold': 200,
 'head': 201,
 'smiling': 202,
 'beautiful': 203,
 'smile': 204,
 'takes': 205,
 'stand': 206,
 'last': 207,
 'again': 208,
 'matters': 209,
 "she's": 210,
 'laugh': 211,
 'human': 212,
 'making': 213,
 'change': 214,
 'nonsense': 215,
 'necessary': 216,
 'living': 217,
 'lack': 218,
 'while': 219,
 'loving': 220,
 'intimate': 221,
 'hand': 222,
 'eyes': 223,
 'happiness': 224,
 '“anyone': 225,
 'thinks': 226,
 'sitting': 227,
 'eye': 228,
 'beholder': 229,
 'children': 230,
 'intelligent': 231,
 'might': 232,
 'imagination': 233,
 'feel': 234,
 'learn': 235,
 'course': 236,
 'inside': 237,
 'real': 238,
 'got': 239,
 '“not': 240,
 'adventure': 241,
 '“we': 242,
 "we're": 243,
 'point': 244,
 'library': 245,
 'been': 246,
 'he': 247,
 'long': 248,
 'into': 249,
 'girl': 250,
 'left': 251,
 'someone': 252,
 'they': 253,
 'grow': 254,
 'does': 255,
 'begin': 256,
 'would': 257,
 '“do': 258,
 'often': 259,
 'between': 260,
 'friend': 261,
 'door': 262,
 "isn't": 263,
 'thought': 264,
 'myself': 265,
 'happen': 266,
 'hope': 267,
 '“remember': 268,
 'vulnerable': 269,
 'broken': 270,
 'safe': 271,
 'casket': 272,
 'pity': 273,
 'new': 274,
 'shall': 275,
 'walk': 276,
 '“some': 277,
 'out': 278,
 'whom': 279,
 'fear': 280,
 'lie': 281,
 'around': 282,
 'his': 283,
 'write': 284,
 'needs': 285,
 'created': 286,
 'process': 287,
 'cannot': 288,
 'changed': 289,
 'changing': 290,
 'choices': 291,
 'show': 292,
 'far': 293,
 'abilities': 294,
 'gentleman': 295,
 'lady': 296,
 'pleasure': 297,
 'novel': 298,
 'intolerably': 299,
 '“imperfection': 300,
 'beauty': 301,
 'madness': 302,
 'ridiculous': 303,
 'boring': 304,
 '“try': 305,
 'success': 306,
 'rather': 307,
 'value': 308,
 'hated': 309,
 'failed': 310,
 'found': 311,
 '10': 312,
 '000': 313,
 "won't": 314,
 'work': 315,
 'bag': 316,
 'strong': 317,
 'hot': 318,
 'water': 319,
 'sunshine': 320,
 'night': 321,
 '“this': 322,
 'sometimes': 323,
 'universal': 324,
 'decide': 325,
 'girls': 326,
 'act': 327,
 'anyway': 328,
 'stay': 329,
 "they're": 330,
 'sisters': 331,
 'lovers': 332,
 'baby': 333,
 'actually': 334,
 'pretty': 335,
 'break': 336,
 'soulmate': 337,
 'whole': 338,
 'goes': 339,
 'once': 340,
 'gonna': 341,
 'sweetie': 342,
 'chin': 343,
 'importantly': 344,
 "life's": 345,
 "there's": 346,
 'deal': 347,
 'bravery': 348,
 'enemies': 349,
 'explain': 350,
 'six': 351,
 'year': 352,
 'first': 353,
 'loves': 354,
 'perfect—you': 355,
 "aren't": 356,
 'either': 357,
 'perfect': 358,
 'together': 359,
 'cause': 360,
 'twice': 361,
 'admit': 362,
 'being': 363,
 'mistakes': 364,
 'onto': 365,
 'second': 366,
 'knows': 367,
 'break—her': 368,
 'analyze': 369,
 'expect': 370,
 'happy': 371,
 'mad': 372,
 'miss': 373,
 'wakes': 374,
 'brain': 375,
 'cells': 376,
 'fantasy': 377,
 'ingredient': 378,
 'gone': 379,
 'intended': 380,
 'ended': 381,
 'needed': 382,
 'art': 383,
 'ugliness': 384,
 'faith': 385,
 'heresy': 386,
 'friendship': 387,
 'unhappy': 388,
 'marriages': 389,
 '“good': 390,
 'sleepy': 391,
 'conscience': 392,
 'ideal': 393,
 'plans': 394,
 'knowing': 395,
 'simply': 396,
 'problems': 397,
 'pride': 398,
 'upon': 399,
 'chest': 400,
 'fall': 401,
 'asleep': 402,
 'close': 403,
 '“for': 404,
 'minute': 405,
 'angry': 406,
 'lose': 407,
 'sixty': 408,
 'seconds': 409,
 'judge': 410,
 'church': 411,
 'christian': 412,
 'garage': 413,
 'car': 414,
 '“beauty': 415,
 'misinformed': 416,
 'black': 417,
 '“today': 418,
 'truer': 419,
 'alive': 420,
 'youer': 421,
 'impossible': 422,
 'failing': 423,
 'unless': 424,
 'cautiously': 425,
 'lived': 426,
 'case': 427,
 'default': 428,
 '“logic': 429,
 'z': 430,
 'everywhere': 431,
 '“one': 432,
 'hits': 433,
 'pain': 434,
 'places': 435,
 '“of': 436,
 'happening': 437,
 'why': 438,
 'earth': 439,
 'worth': 440,
 'suffering': 441,
 'organized': 442,
 'next': 443,
 '“all': 444,
 'need': 445,
 'chocolate': 446,
 'alone': 447,
 '“any': 448,
 'fool': 449,
 'imagined': 450,
 'paradise': 451,
 'late': 452,
 'reader': 453,
 'thousand': 454,
 'dies': 455,
 'said': 456,
 'jojen': 457,
 'reads': 458,
 'cup': 459,
 'large': 460,
 'suit': 461,
 'lies': 462,
 'eventually': 463,
 'trust': 464,
 'riding': 465,
 'bicycle': 466,
 'balance': 467,
 'moving': 468,
 'lover': 469,
 'thrill': 470,
 'kissing': 471,
 'forehead': 472,
 'staring': 473,
 'space': 474,
 'wise': 475,
 'kisses': 476,
 'listens': 477,
 'leaves': 478,
 '“only': 479,
 'darkness': 480,
 'stars': 481,
 'born': 482,
 '“love': 483,
 'end': 484,
 'seem': 485,
 'battle': 486,
 'war': 487,
 'growing': 488,
 'notion': 489,
 'halves': 490,
 'nature': 491,
 'scares': 492,
 'angel': 493,
 'sin': 494,
 'devil': 495,
 'were': 496,
 'physicist': 497,
 'probably': 498,
 'musician': 499,
 'daydreams': 500,
 'terms': 501,
 'difference': 502,
 'stupidity': 503,
 'limits': 504,
 "“he's": 505,
 'drug': 506,
 'bella': 507,
 'loyal': 508,
 '“when': 509,
 'closes': 510,
 'another': 511,
 'opens': 512,
 'look': 513,
 'closed': 514,
 'opened': 515,
 'finding': 516,
 'creating': 517,
 "“that's": 518,
 'problem': 519,
 'drinking': 520,
 'poured': 521,
 'bad': 522,
 'attempt': 523,
 'order': 524,
 'celebrate': 525,
 'don’t': 526,
 'face': 527,
 'madly': 528,
 'kiss': 529,
 'anytime': 530,
 'wrung': 531,
 'possibly': 532,
 'sure': 533,
 'keeping': 534,
 'intact': 535,
 'even': 536,
 'animal': 537,
 'wrap': 538,
 'carefully': 539,
 'round': 540,
 'hobbies': 541,
 'luxuries': 542,
 'avoid': 543,
 'entanglements': 544,
 'lock': 545,
 'coffin': 546,
 'selfishness': 547,
 'dark': 548,
 'motionless': 549,
 'airless': 550,
 'unbreakable': 551,
 'impenetrable': 552,
 'irredeemable': 553,
 'wander': 554,
 'lost': 555,
 'dead': 556,
 'above': 557,
 'writing': 558,
 'sit': 559,
 'down': 560,
 'typewriter': 561,
 'bleed': 562,
 '“finish': 563,
 'each': 564,
 'blunders': 565,
 'absurdities': 566,
 'doubt': 567,
 'crept': 568,
 'soon': 569,
 'tomorrow': 570,
 'serenely': 571,
 'spirit': 572,
 'encumbered': 573,
 'schooling': 574,
 'interfere': 575,
 'education': 576,
 'heard': 577,
 'ahead': 578,
 'behind': 579,
 'bought': 580,
 'bat': 581,
 'ready': 582,
 'had': 583,
 'flower': 584,
 'garden': 585,
 'forever': 586,
 'crazy': 587,
 'horrible': 588,
 'lead': 589,
 'trouble': 590,
 'having': 591,
 'open': 592,
 'insist': 593,
 'coming': 594,
 'along': 595,
 'put': 596,
 '“think': 597,
 'low': 598,
 'oh': 599,
 'try': 600,
 '“what': 601,
 'knocks': 602,
 'wish': 603,
 'author': 604,
 'wrote': 605,
 'terrific': 606,
 'yours': 607,
 'call': 608,
 'him': 609,
 'phone': 610,
 'whenever': 611,
 'felt': 612,
 'reason': 613,
 'talk': 614,
 'i’m': 615,
 'whose': 616,
 'answers': 617,
 'accept': 618,
 'dreamer': 619,
 'someday': 620,
 'join': 621,
 'free': 622,
 'prejudice': 623,
 'equally': 624,
 'question': 625,
 'stop': 626,
 '“′classic′': 627,
 'praise': 628,
 'made': 629,
 'mistake': 630,
 'tried': 631,
 "lady's": 632,
 'very': 633,
 'rapid': 634,
 'jumps': 635,
 'admiration': 636,
 'matrimony': 637,
 'moment': 638,
 'choice': 639,
 'easy': 640,
 'happened': 641,
 'boy': 642,
 'brave': 643,
 'strayed': 644,
 'across': 645,
 'path': 646,
 'lord': 647,
 'voldemort': 648,
 'cedric': 649,
 'diggory': 650,
 'declare': 651,
 'after': 652,
 'enjoyment': 653,
 'sooner': 654,
 'tires': 655,
 'house': 656,
 'own': 657,
 'miserable': 658,
 'excellent': 659,
 'few': 660,
 'still': 661,
 'fewer': 662,
 'dissatisfied': 663,
 'confirms': 664,
 'belief': 665,
 'inconsistency': 666,
 'characters': 667,
 'dependence': 668,
 'placed': 669,
 'appearance': 670,
 'merit': 671,
 'sense': 672,
 'start': 673,
 'necessarily': 674,
 'doubting': 675,
 'god': 676,
 'wondering': 677,
 'painful': 678,
 'turn': 679,
 'follows': 680,
 'fully': 681,
 'prepared': 682,
 'travel': 683,
 'putting': 684,
 'shoes': 685,
 'christianity': 686,
 'sun': 687,
 'risen': 688,
 'dumbledore': 689,
 'sighed': 690,
 'terrible': 691,
 'therefore': 692,
 'treated': 693,
 'caution': 694,
 "“i'm": 695,
 "that's": 696,
 'awfully': 697,
 'courage': 698,
 '“but': 699,
 'comforted': 700,
 'consider': 701,
 'view': 702,
 'climb': 703,
 'skin': 704,
 'wants': 705,
 'written': 706,
 'difficult': 707,
 'grown': 708,
 'ups': 709,
 '“never': 710,
 'tell': 711,
 'worthy': 712,
 "person's": 713,
 '“': 714,
 'sword': 715,
 'whetstone': 716,
 'edge': 717}

In [260]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9, 288, 12, 289, 76, 290, 75, 109, 1], [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293, 36, 45, 75, 294, 1], [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110, 4, 6, 181, 5, 137, 4, 24, 136, 86, 4, 6, 181, 1], [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6, 58, 298, 87, 12, 299, 182, 1], [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183, 303, 45, 183, 304, 1], [305, 11, 3, 112, 6, 88, 7, 306, 307, 112, 6, 88, 7, 308, 1], [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29, 23, 2, 22, 11, 1], [37, 21, 11, 310, 185, 59, 311, 312, 313, 180, 13, 314, 315, 1], [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9, 4, 140, 41, 14, 318, 319, 1], [60, 62, 76, 320, 4, 47, 2, 61, 321, 1], [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189, 26, 323, 41, 6, 324, 79, 15, 5, 58, 190, 4, 2, 89, 3, 325, 78, 113, 63, 3, 189, 9, 26, 326, 20, 12, 18, 80, 191, 327, 47, 9, 328, 15, 59, 114, 90, 91, 90, 81, 5, 192, 13, 329, 30, 2, 193, 86, 330, 18, 194, 115, 80, 54, 92, 81, 7, 55, 195, 114, 331, 42, 5, 115, 80, 14, 5, 74, 24, 29, 332, 116, 191, 91, 8, 81, 117, 8, 333, 10, 141, 3, 196, 9, 142, 7, 55, 334, 335, 93, 27, 7, 55, 22, 63, 3, 336, 18, 143, 15, 2, 197, 64, 26, 48, 28, 2, 64, 26, 118, 34, 119, 18, 337, 118, 34, 119, 13, 198, 19, 120, 2, 338, 8, 13, 339, 29, 86, 59, 48, 2, 144, 340, 94, 199, 113, 341, 144, 65, 86, 66, 145, 200, 82, 8, 121, 121, 121, 95, 14, 96, 48, 28, 2, 54, 146, 19, 20, 342, 43, 66, 18, 201, 147, 66, 18, 343, 26, 8, 142, 344, 66, 202, 48, 345, 6, 203, 97, 8, 346, 43, 93, 3, 204, 98, 1], [52, 205, 6, 99, 347, 7, 348, 3, 206, 26, 3, 75, 349, 15, 59, 24, 93, 3, 206, 26, 3, 75, 80, 1], [67, 2, 197, 350, 9, 3, 6, 351, 352, 148, 2, 54, 149, 9, 96, 1], [68, 69, 11, 12, 38, 353, 38, 207, 33, 38, 46, 39, 184, 150, 39, 69, 16, 208, 15, 28, 39, 354, 2, 151, 23, 122, 209, 210, 11, 355, 356, 357, 8, 5, 179, 7, 2, 69, 34, 12, 358, 359, 15, 28, 39, 17, 42, 2, 211, 360, 2, 3, 40, 361, 8, 362, 3, 363, 212, 8, 213, 364, 200, 365, 38, 8, 64, 38, 5, 142, 2, 17, 39, 69, 11, 12, 109, 98, 2, 100, 366, 7, 5, 62, 15, 39, 20, 64, 2, 6, 190, 7, 38, 13, 39, 367, 2, 17, 368, 143, 43, 54, 123, 38, 54, 214, 38, 54, 369, 8, 54, 370, 36, 45, 39, 17, 64, 204, 44, 39, 120, 2, 371, 92, 38, 61, 44, 39, 120, 2, 372, 8, 373, 38, 44, 210, 11, 101, 1], [37, 47, 215, 9, 374, 26, 5, 375, 376, 377, 4, 6, 216, 378, 14, 217, 1], [37, 69, 11, 21, 379, 152, 10, 380, 3, 81, 15, 10, 40, 10, 21, 381, 26, 152, 10, 382, 3, 12, 1], [32, 124, 7, 16, 4, 11, 141, 41, 125, 5, 124, 7, 383, 4, 11, 384, 41, 125, 5, 124, 7, 385, 4, 11, 386, 41, 125, 8, 5, 124, 7, 53, 4, 11, 153, 41, 125, 1], [52, 4, 11, 6, 218, 7, 16, 15, 6, 218, 7, 387, 13, 120, 388, 389, 1], [390, 80, 58, 154, 8, 6, 391, 392, 155, 4, 5, 393, 53, 1], [156, 4, 23, 126, 3, 102, 219, 51, 22, 213, 137, 394, 1], [37, 16, 2, 76, 395, 78, 33, 44, 33, 49, 152, 10, 16, 2, 396, 76, 397, 33, 398, 10, 16, 2, 14, 155, 103, 48, 10, 50, 11, 61, 157, 137, 103, 7, 220, 15, 155, 14, 127, 101, 4, 35, 10, 33, 2, 43, 221, 13, 18, 222, 399, 31, 400, 4, 31, 222, 43, 221, 13, 44, 10, 401, 402, 18, 223, 403, 1], [404, 100, 405, 2, 22, 406, 2, 407, 408, 409, 7, 224, 1], [67, 2, 410, 70, 2, 21, 35, 71, 3, 16, 55, 1], [225, 19, 226, 227, 14, 411, 17, 42, 2, 6, 412, 87, 195, 40, 13, 227, 14, 6, 413, 17, 42, 2, 6, 414, 1], [415, 4, 14, 5, 228, 7, 5, 229, 8, 9, 69, 12, 216, 49, 71, 3, 71, 3, 64, 6, 182, 33, 416, 229, 6, 417, 228, 1], [418, 2, 22, 2, 13, 4, 419, 45, 194, 101, 4, 35, 25, 420, 19, 4, 421, 45, 2, 1], [67, 2, 128, 18, 230, 3, 12, 231, 83, 55, 158, 159, 28, 2, 128, 55, 3, 12, 36, 231, 83, 55, 36, 158, 159, 1], [52, 4, 422, 3, 57, 76, 423, 65, 129, 424, 2, 57, 43, 425, 13, 2, 232, 24, 116, 11, 21, 426, 65, 27, 14, 127, 427, 2, 144, 104, 428, 1], [429, 20, 89, 2, 49, 6, 3, 430, 233, 20, 89, 2, 431, 1], [432, 58, 97, 98, 130, 44, 9, 433, 2, 2, 234, 35, 434, 1], [32, 36, 13, 2, 83, 5, 36, 105, 2, 20, 61, 5, 36, 13, 2, 235, 5, 36, 435, 118, 81, 1], [436, 236, 9, 4, 437, 237, 18, 201, 135, 15, 438, 82, 439, 160, 13, 199, 13, 9, 4, 11, 238, 1], [32, 79, 4, 131, 4, 63, 3, 123, 2, 2, 59, 239, 3, 119, 5, 192, 440, 441, 29, 1], [240, 27, 7, 102, 17, 50, 99, 105, 15, 51, 17, 50, 161, 105, 30, 99, 16, 1], [162, 5, 116, 442, 163, 153, 4, 15, 5, 443, 99, 241, 1], [444, 2, 445, 4, 16, 15, 6, 164, 446, 151, 8, 146, 94, 123, 1], [242, 83, 3, 61, 243, 11, 447, 1], [448, 449, 17, 61, 5, 244, 4, 3, 149, 1], [37, 21, 121, 450, 13, 451, 20, 12, 6, 165, 7, 245, 1], [52, 4, 34, 117, 452, 3, 12, 23, 2, 232, 21, 246, 1], [60, 453, 106, 6, 454, 106, 150, 247, 455, 456, 457, 5, 88, 19, 34, 458, 106, 46, 25, 1], [68, 17, 34, 89, 6, 459, 7, 187, 460, 166, 33, 6, 72, 248, 166, 3, 461, 56, 1], [68, 95, 462, 43, 2, 463, 235, 3, 464, 35, 25, 15, 96, 1], [67, 2, 17, 42, 6, 186, 211, 2, 17, 42, 38, 50, 167, 1], [156, 4, 47, 465, 6, 466, 3, 66, 18, 467, 2, 87, 66, 468, 1], [32, 238, 469, 4, 5, 88, 19, 17, 470, 2, 104, 471, 18, 472, 33, 202, 249, 18, 223, 33, 59, 473, 249, 474, 1], [60, 475, 250, 476, 15, 94, 16, 477, 15, 94, 95, 8, 478, 150, 39, 4, 251, 1], [479, 14, 5, 480, 17, 2, 73, 5, 481, 1], [52, 209, 11, 23, 252, 4, 482, 15, 23, 253, 254, 3, 12, 1], [483, 255, 11, 256, 8, 484, 5, 103, 51, 485, 3, 40, 9, 255, 16, 4, 6, 486, 16, 4, 6, 487, 16, 4, 6, 488, 26, 1], [85, 4, 110, 10, 257, 11, 50, 29, 168, 19, 22, 107, 31, 80, 10, 21, 35, 489, 7, 220, 70, 104, 490, 9, 4, 11, 31, 491, 1], [258, 25, 97, 100, 62, 13, 492, 2, 1], [37, 108, 58, 15, 11, 84, 493, 10, 50, 494, 15, 10, 108, 11, 5, 495, 10, 108, 59, 6, 161, 250, 14, 6, 169, 74, 145, 3, 119, 252, 3, 16, 1], [67, 10, 496, 11, 6, 497, 10, 257, 498, 12, 6, 499, 10, 259, 40, 14, 130, 10, 57, 31, 500, 14, 130, 10, 73, 31, 53, 14, 501, 7, 130, 1], [67, 2, 46, 83, 5, 154, 13, 131, 122, 4, 132, 2, 17, 46, 40, 23, 131, 122, 4, 109, 1], [32, 502, 260, 138, 8, 503, 4, 138, 77, 170, 504, 1], [505, 47, 6, 506, 29, 2, 507, 1], [85, 4, 35, 261, 24, 508, 24, 6, 72, 1], [509, 25, 262, 7, 224, 510, 511, 512, 15, 259, 51, 513, 43, 248, 65, 5, 514, 262, 13, 51, 50, 11, 73, 5, 25, 127, 77, 246, 515, 29, 102, 1], [156, 263, 98, 516, 96, 53, 4, 98, 517, 96, 1], [518, 5, 519, 30, 520, 10, 264, 24, 10, 521, 265, 6, 133, 28, 129, 522, 126, 2, 133, 14, 84, 523, 3, 171, 28, 129, 58, 126, 2, 133, 14, 524, 3, 525, 8, 28, 110, 126, 2, 133, 3, 42, 129, 266, 1], [68, 526, 171, 5, 527, 7, 5, 111, 19, 172, 18, 207, 267, 1], [268, 243, 528, 14, 16, 43, 41, 27, 173, 3, 529, 56, 530, 2, 234, 47, 9, 1], [162, 16, 65, 27, 4, 3, 12, 269, 16, 167, 8, 18, 143, 20, 12, 531, 8, 532, 270, 28, 2, 128, 3, 42, 533, 7, 534, 9, 535, 2, 87, 64, 9, 3, 35, 25, 11, 536, 84, 537, 538, 9, 539, 540, 30, 541, 8, 164, 542, 543, 27, 544, 545, 9, 26, 271, 14, 5, 272, 33, 546, 7, 18, 547, 15, 14, 13, 272, 271, 548, 549, 550, 9, 20, 214, 9, 20, 11, 12, 270, 9, 20, 112, 551, 552, 553, 3, 16, 4, 3, 12, 269, 1], [240, 27, 168, 19, 554, 22, 555, 1], [258, 11, 273, 5, 556, 135, 273, 5, 217, 8, 557, 27, 168, 19, 57, 76, 16, 1], [85, 4, 110, 3, 558, 27, 2, 50, 4, 559, 560, 65, 6, 561, 8, 562, 1], [563, 564, 62, 8, 12, 174, 30, 9, 2, 21, 174, 23, 2, 175, 90, 565, 8, 566, 35, 567, 568, 14, 171, 55, 24, 569, 24, 2, 17, 570, 4, 6, 274, 62, 2, 275, 256, 9, 571, 8, 30, 117, 147, 6, 572, 3, 12, 573, 30, 18, 148, 215, 1], [37, 21, 34, 92, 31, 574, 575, 30, 31, 576, 1], [37, 21, 577, 101, 22, 176, 7, 36, 45, 25, 165, 90, 91, 49, 578, 8, 90, 91, 49, 579, 15, 185, 580, 6, 169, 581, 177, 27, 582, 2, 73, 151, 31, 176, 22, 63, 3, 21, 176, 30, 56, 1], [67, 10, 583, 6, 584, 29, 100, 71, 10, 264, 7, 2, 10, 175, 276, 193, 31, 585, 586, 1], [277, 70, 34, 81, 587, 23, 178, 588, 106, 253, 87, 589, 1], [32, 590, 30, 591, 84, 592, 163, 7, 236, 4, 13, 70, 20, 593, 82, 594, 595, 8, 145, 3, 596, 105, 14, 9, 1], [597, 251, 8, 40, 173, 8, 40, 598, 8, 40, 147, 599, 5, 226, 2, 17, 40, 26, 28, 46, 2, 600, 1], [601, 107, 602, 56, 278, 4, 6, 72, 13, 44, 113, 27, 174, 132, 9, 2, 603, 5, 604, 13, 605, 9, 172, 6, 606, 261, 7, 607, 8, 2, 175, 608, 609, 26, 82, 5, 610, 611, 2, 612, 47, 9, 13, 94, 266, 93, 136, 1], [32, 613, 10, 614, 3, 265, 4, 48, 615, 5, 46, 25, 616, 617, 10, 618, 1], [68, 69, 196, 177, 6, 619, 15, 177, 11, 5, 46, 25, 10, 267, 620, 118, 621, 102, 8, 5, 74, 20, 57, 24, 25, 1], [37, 108, 622, 7, 27, 623, 10, 141, 131, 624, 1], [32, 625, 263, 19, 4, 63, 3, 92, 56, 41, 19, 4, 63, 3, 626, 56, 1], [627, 6, 72, 127, 70, 628, 8, 54, 83, 1], [225, 19, 77, 34, 629, 6, 630, 77, 34, 631, 167, 274, 1], [60, 632, 233, 4, 633, 634, 9, 635, 49, 636, 3, 16, 49, 16, 3, 637, 14, 6, 638, 1], [268, 28, 5, 71, 160, 91, 44, 2, 21, 3, 42, 6, 639, 260, 23, 4, 173, 8, 23, 4, 640, 114, 23, 641, 3, 6, 642, 19, 172, 58, 8, 165, 8, 643, 48, 247, 644, 645, 5, 646, 7, 647, 648, 114, 649, 650, 1], [37, 651, 652, 27, 101, 4, 35, 653, 47, 132, 78, 93, 654, 25, 655, 7, 157, 97, 45, 7, 6, 72, 44, 10, 21, 6, 656, 7, 31, 657, 10, 275, 12, 658, 28, 10, 21, 11, 84, 659, 245, 1], [85, 22, 660, 70, 279, 10, 107, 16, 8, 661, 662, 7, 279, 10, 40, 116, 5, 36, 10, 73, 7, 5, 74, 5, 36, 108, 10, 663, 30, 9, 8, 100, 62, 664, 31, 665, 7, 5, 666, 7, 27, 212, 667, 8, 7, 5, 164, 668, 13, 17, 12, 669, 82, 5, 670, 7, 671, 33, 672, 1], [277, 62, 2, 20, 12, 148, 166, 3, 673, 132, 158, 159, 208, 1], [242, 22, 11, 674, 675, 13, 676, 20, 50, 5, 115, 29, 102, 51, 22, 677, 78, 678, 5, 115, 20, 679, 278, 3, 12, 1], [32, 280, 7, 153, 680, 49, 5, 280, 7, 53, 6, 88, 19, 106, 681, 4, 682, 3, 134, 65, 157, 71, 1], [60, 281, 17, 683, 198, 103, 282, 5, 74, 219, 5, 79, 4, 684, 82, 170, 685, 1], [37, 95, 14, 686, 24, 10, 95, 13, 5, 687, 77, 688, 11, 46, 48, 10, 73, 9, 15, 48, 104, 9, 10, 73, 86, 122, 1], [32, 79, 689, 690, 9, 4, 6, 203, 8, 691, 97, 8, 160, 692, 12, 693, 30, 99, 694, 1], [695, 5, 25, 696, 239, 3, 134, 44, 41, 71, 29, 56, 3, 134, 43, 92, 56, 57, 31, 53, 5, 103, 10, 128, 3, 1], [162, 134, 20, 12, 84, 697, 169, 241, 1], [52, 205, 698, 3, 254, 26, 8, 112, 19, 2, 107, 22, 1], [699, 139, 3, 89, 123, 104, 5, 79, 45, 700, 30, 6, 281, 1], [68, 34, 107, 149, 6, 111, 140, 2, 701, 105, 49, 283, 244, 7, 702, 140, 2, 703, 237, 7, 283, 704, 8, 276, 282, 14, 9, 1], [68, 21, 3, 284, 5, 72, 13, 705, 3, 12, 706, 8, 28, 5, 72, 20, 12, 117, 707, 29, 708, 709, 146, 2, 284, 9, 29, 230, 1], [710, 711, 5, 79, 3, 70, 19, 22, 11, 712, 7, 9, 1], [60, 713, 6, 111, 35, 188, 78, 161, 1], [714, 6, 163, 285, 154, 24, 6, 715, 285, 6, 716, 28, 9, 4, 3, 66, 170, 717, 1]]

In [261]:
input_sequences = []
for sentence in sentences:
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1, len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [262]:
input_sequences

[[32, 74],
 [32, 74, 24],
 [32, 74, 24, 51],
 [32, 74, 24, 51, 21],
 [32, 74, 24, 51, 21, 286],
 [32, 74, 24, 51, 21, 286, 9],
 [32, 74, 24, 51, 21, 286, 9, 4],
 [32, 74, 24, 51, 21, 286, 9, 4, 6],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9, 288],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9, 288, 12],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9, 288, 12, 289],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9, 288, 12, 289, 76],
 [32, 74, 24, 51, 21, 286, 9, 4, 6, 287, 7, 75, 109, 9, 288, 12, 289, 76, 290],
 [32,
  74,
  24,
  51,
  21,
  286,
  9,
  4,
  6,
  287,
  7,
  75,
  109,
  9,
  288,
  12,
  289,
  76,
  290,
  75],
 [32,
  74,
  24,
  51,
  21,
  286,
  9,
  4,
  6,
  287,
  7,
  75,
  109,
  9,
  288,
  12,
  289,
  76,
  290,
  75,
  109],
 [32,
  74,
  24,
  51,
  21,
  286,
  9,
  4,
  6,
  287,
  7,
  75,
  109,
  9,
  288,
  12,
  289,
  76,
  290,
  75,
  109,
  1],
 [52, 4],
 [52, 4, 75],
 [52, 4, 75, 291],
 [52, 4, 75, 291, 135],
 [52, 4, 75, 291, 135, 13],
 [52, 4, 75, 291, 135, 13, 292],
 [52, 4, 75, 291, 135, 13, 292, 23],
 [52, 4, 75, 291, 135, 13, 292, 23, 51],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293, 36],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293, 36, 45],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293, 36, 45, 75],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293, 36, 45, 75, 294],
 [52, 4, 75, 291, 135, 13, 292, 23, 51, 178, 22, 293, 36, 45, 75, 294, 1],
 [85, 22],
 [85, 22, 46],
 [85, 22, 46, 179],
 [85, 22, 46, 179, 180],
 [85, 22, 46, 179, 180, 3],
 [85, 22, 46, 179, 180, 3, 57],
 [85, 22, 46, 179, 180, 3, 57, 18],
 [85, 22, 46, 179, 180, 3, 57, 18, 53],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110, 4],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110, 4, 6],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110, 4, 6, 181],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110, 4, 6, 181, 5],
 [85, 22, 46, 179, 180, 3, 57, 18, 53, 25, 4, 24, 136, 110, 4, 6, 181, 5, 137],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24,
  136],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24,
  136,
  86],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24,
  136,
  86,
  4],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24,
  136,
  86,
  4,
  6],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24,
  136,
  86,
  4,
  6,
  181],
 [85,
  22,
  46,
  179,
  180,
  3,
  57,
  18,
  53,
  25,
  4,
  24,
  136,
  110,
  4,
  6,
  181,
  5,
  137,
  4,
  24,
  136,
  86,
  4,
  6,
  181,
  1],
 [32, 111],
 [32, 111, 12],
 [32, 111, 12, 9],
 [32, 111, 12, 9, 295],
 [32, 111, 12, 9, 295, 33],
 [32, 111, 12, 9, 295, 33, 296],
 [32, 111, 12, 9, 295, 33, 296, 19],
 [32, 111, 12, 9, 295, 33, 296, 19, 77],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6, 58],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6, 58, 298],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6, 58, 298, 87],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6, 58, 298, 87, 12],
 [32, 111, 12, 9, 295, 33, 296, 19, 77, 11, 297, 14, 6, 58, 298, 87, 12, 299],
 [32,
  111,
  12,
  9,
  295,
  33,
  296,
  19,
  77,
  11,
  297,
  14,
  6,
  58,
  298,
  87,
  12,
  299,
  182],
 [32,
  111,
  12,
  9,
  295,
  33,
  296,
  19,
  77,
  11,
  297,
  14,
  6,
  58,
  298,
  87,
  12,
  299,
  182,
  1],
 [300, 4],
 [300, 4, 301],
 [300, 4, 301, 302],
 [300, 4, 301, 302, 4],
 [300, 4, 301, 302, 4, 138],
 [300, 4, 301, 302, 4, 138, 8],
 [300, 4, 301, 302, 4, 138, 8, 41],
 [300, 4, 301, 302, 4, 138, 8, 41, 139],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183, 303],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183, 303, 45],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183, 303, 45, 183],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183, 303, 45, 183, 304],
 [300, 4, 301, 302, 4, 138, 8, 41, 139, 3, 12, 183, 303, 45, 183, 304, 1],
 [305, 11],
 [305, 11, 3],
 [305, 11, 3, 112],
 [305, 11, 3, 112, 6],
 [305, 11, 3, 112, 6, 88],
 [305, 11, 3, 112, 6, 88, 7],
 [305, 11, 3, 112, 6, 88, 7, 306],
 [305, 11, 3, 112, 6, 88, 7, 306, 307],
 [305, 11, 3, 112, 6, 88, 7, 306, 307, 112],
 [305, 11, 3, 112, 6, 88, 7, 306, 307, 112, 6],
 [305, 11, 3, 112, 6, 88, 7, 306, 307, 112, 6, 88],
 [305, 11, 3, 112, 6, 88, 7, 306, 307, 112, 6, 88, 7],
 [305, 11, 3, 112, 6, 88, 7, 306, 307, 112, 6, 88, 7, 308],
 [305, 11, 3, 112, 6, 88, 7, 306, 307, 112, 6, 88, 7, 308, 1],
 [52, 4],
 [52, 4, 139],
 [52, 4, 139, 3],
 [52, 4, 139, 3, 12],
 [52, 4, 139, 3, 12, 309],
 [52, 4, 139, 3, 12, 309, 29],
 [52, 4, 139, 3, 12, 309, 29, 23],
 [52, 4, 139, 3, 12, 309, 29, 23, 2],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29, 23],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29, 23, 2],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29, 23, 2, 22],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29, 23, 2, 22, 11],
 [52, 4, 139, 3, 12, 309, 29, 23, 2, 22, 45, 3, 12, 184, 29, 23, 2, 22, 11, 1],
 [37, 21],
 [37, 21, 11],
 [37, 21, 11, 310],
 [37, 21, 11, 310, 185],
 [37, 21, 11, 310, 185, 59],
 [37, 21, 11, 310, 185, 59, 311],
 [37, 21, 11, 310, 185, 59, 311, 312],
 [37, 21, 11, 310, 185, 59, 311, 312, 313],
 [37, 21, 11, 310, 185, 59, 311, 312, 313, 180],
 [37, 21, 11, 310, 185, 59, 311, 312, 313, 180, 13],
 [37, 21, 11, 310, 185, 59, 311, 312, 313, 180, 13, 314],
 [37, 21, 11, 310, 185, 59, 311, 312, 313, 180, 13, 314, 315],
 [37, 21, 11, 310, 185, 59, 311, 312, 313, 180, 13, 314, 315, 1],
 [60, 186],
 [60, 186, 4],
 [60, 186, 4, 47],
 [60, 186, 4, 47, 6],
 [60, 186, 4, 47, 6, 187],
 [60, 186, 4, 47, 6, 187, 316],
 [60, 186, 4, 47, 6, 187, 316, 2],
 [60, 186, 4, 47, 6, 187, 316, 2, 34],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9, 4],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9, 4, 140],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9, 4, 140, 41],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9, 4, 140, 41, 14],
 [60, 186, 4, 47, 6, 187, 316, 2, 34, 61, 78, 317, 9, 4, 140, 41, 14, 318],
 [60,
  186,
  4,
  47,
  6,
  187,
  316,
  2,
  34,
  61,
  78,
  317,
  9,
  4,
  140,
  41,
  14,
  318,
  319],
 [60,
  186,
  4,
  47,
  6,
  187,
  316,
  2,
  34,
  61,
  78,
  317,
  9,
  4,
  140,
  41,
  14,
  318,
  319,
  1],
 [60, 62],
 [60, 62, 76],
 [60, 62, 76, 320],
 [60, 62, 76, 320, 4],
 [60, 62, 76, 320, 4, 47],
 [60, 62, 76, 320, 4, 47, 2],
 [60, 62, 76, 320, 4, 47, 2, 61],
 [60, 62, 76, 320, 4, 47, 2, 61, 321],
 [60, 62, 76, 320, 4, 47, 2, 61, 321, 1],
 [322, 53],
 [322, 53, 4],
 [322, 53, 4, 23],
 [322, 53, 4, 23, 2],
 [322, 53, 4, 23, 2, 42],
 [322, 53, 4, 23, 2, 42, 9],
 [322, 53, 4, 23, 2, 42, 9, 35],
 [322, 53, 4, 23, 2, 42, 9, 35, 188],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189, 26],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189, 26, 323],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189, 26, 323, 41],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189, 26, 323, 41, 6],
 [322, 53, 4, 23, 2, 42, 9, 35, 188, 23, 113, 63, 3, 189, 26, 323, 41, 6, 324],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192,
  13],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192,
  13,
  329],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192,
  13,
  329,
  30],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192,
  13,
  329,
  30,
  2],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192,
  13,
  329,
  30,
  2,
  193],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,
  191,
  327,
  47,
  9,
  328,
  15,
  59,
  114,
  90,
  91,
  90,
  81,
  5,
  192,
  13,
  329,
  30,
  2,
  193,
  86],
 [322,
  53,
  4,
  23,
  2,
  42,
  9,
  35,
  188,
  23,
  113,
  63,
  3,
  189,
  26,
  323,
  41,
  6,
  324,
  79,
  15,
  5,
  58,
  190,
  4,
  2,
  89,
  3,
  325,
  78,
  113,
  63,
  3,
  189,
  9,
  26,
  326,
  20,
  12,
  18,
  80,

In [263]:
max_len = max([len(x) for x in input_sequences])

In [264]:
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

In [265]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  32,  74],
       [  0,   0,   0, ...,  32,  74,  24],
       [  0,   0,   0, ...,  74,  24,  51],
       ...,
       [  0,   0,   0, ...,   3,  66, 170],
       [  0,   0,   0, ...,  66, 170, 717],
       [  0,   0,   0, ..., 170, 717,   1]], dtype=int32)

In [266]:
X = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [267]:
X.shape

(2360, 198)

In [268]:
y.shape

(2360,)

In [269]:
len(tokenizer.index_word)

717

In [270]:
y = to_categorical(y,num_classes=718)

In [271]:
y.shape

(2360, 718)

In [272]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [273]:
model = Sequential()
model.add(Embedding(718, 100,input_length=198,input_shape=(198,)))
model.add(LSTM(150))
model.add(Dense(718, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [274]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [275]:
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_16 (Embedding)        │ (None, 198, 100)       │        71,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_20 (LSTM)                  │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 718)            │       108,418 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 330,818 (1.26 MB)

 Trainable params: 330,818 (1.26 MB)

 Non-trainable params: 0 (0.00 B)

In [276]:
model.fit(X,y,epochs=100,batch_size=128)

Epoch 1/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - accuracy: 0.0229 - loss: 6.3730
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - accuracy: 0.0326 - loss: 5.7171
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 801ms/step - accuracy: 0.0314 - loss: 5.6202
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 801ms/step - accuracy: 0.0424 - loss: 5.5900
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 794ms/step - accuracy: 0.0424 - loss: 5.5789
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 22s 820ms/step - accuracy: 0.0564 - loss: 5.5607
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 787ms/step - accuracy: 0.0623 - loss: 5.5319
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 858ms/step - accuracy: 0.0631 - loss: 5.4884
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 809ms/step - accuracy: 0.0614 - loss: 5.4238
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 779ms/step - accuracy: 0.0720 - loss: 5.3569
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 785ms/step - accuracy: 0.0644 - loss: 5.2857
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 778ms/step - accuracy: 0.0720 - loss: 5.2207
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 798ms/step - accuracy: 0.0818 - loss: 5.1609
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 783ms/step - accuracy: 0.0945 - loss: 5.0892
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 785ms/step - accuracy: 0.1064 - loss: 5.0239
Epoch 16/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 776ms/step - accuracy: 0.1093 - loss: 4.9532
Epoch 17/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 869ms/step - accuracy: 0.1161 - loss: 4.8793
Epoch 18/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 798ms/step - accuracy: 0.1428 - loss: 4.8039
Epoch 19/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 814ms/step - accuracy: 0.1432 - loss: 4.7286
Epoch 20/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 813ms/step - accuracy: 0.1585 - loss: 4.6528
Epoch 21/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 836ms/step - accuracy: 0.1691 - loss: 4.5783
Epoch 22/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 17s 860ms/step - accuracy: 0.1746 - loss: 4.4976
Epoch 23/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 797ms/step - accuracy: 0.1784 - loss: 4.4222
Epoch 24/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 801ms/step - accuracy: 0.1890 - loss: 4.3446
Epoch 25/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 801ms/step - accuracy: 0.1941 - loss: 4.2687
Epoch 26/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 807ms/step - accuracy: 0.2051 - loss: 4.1966
Epoch 27/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 17s 868ms/step - accuracy: 0.2165 - loss: 4.1146
Epoch 28/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 838ms/step - accuracy: 0.2254 - loss: 4.0395
Epoch 29/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 805ms/step - accuracy: 0.2318 - loss: 3.9631
Epoch 30/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 17s 867ms/step - accuracy: 0.2398 - loss: 3.8879
Epoch 31/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 779ms/step - accuracy: 0.2513 - loss: 3.8156
Epoch 32/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 769ms/step - accuracy: 0.2585 - loss: 3.7409
Epoch 33/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 788ms/step - accuracy: 0.2720 - loss: 3.6679
Epoch 34/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 21s 795ms/step - accuracy: 0.2788 - loss: 3.5947
Epoch 35/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 793ms/step - accuracy: 0.2932 - loss: 3.5215
Epoch 36/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 829ms/step - accuracy: 0.2958 - loss: 3.4486
Epoch 37/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 789ms/step - accuracy: 0.3127 - loss: 3.3798
Epoch 38/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 837ms/step - accuracy: 0.3174 - loss: 3.3091
Epoch 39/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 788ms/step - accuracy: 0.3297 - loss: 3.2394
Epoch 40/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 21s 786ms/step - accuracy: 0.3386 - loss: 3.1682
Epoch 41/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 788ms/step - accuracy: 0.3496 - loss: 3.0988
Epoch 42/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 814ms/step - accuracy: 0.3593 - loss: 3.0315
Epoch 43/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 784ms/step - accuracy: 0.3669 - loss: 2.9653
Epoch 44/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 21s 792ms/step - accuracy: 0.3797 - loss: 2.8967
Epoch 45/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 777ms/step - accuracy: 0.3941 - loss: 2.8342
Epoch 46/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 851ms/step - accuracy: 0.4034 - loss: 2.7706
Epoch 47/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 19s 795ms/step - accuracy: 0.4136 - loss: 2.7051
Epoch 48/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 793ms/step - accuracy: 0.4297 - loss: 2.6360
Epoch 49/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 849ms/step - accuracy: 0.4419 - loss: 2.5783
Epoch 50/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 19s 787ms/step - accuracy: 0.4547 - loss: 2.5196
Epoch 51/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 793ms/step - accuracy: 0.4614 - loss: 2.4605
Epoch 52/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 790ms/step - accuracy: 0.4758 - loss: 2.3969
Epoch 53/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 783ms/step - accuracy: 0.4936 - loss: 2.3420
Epoch 54/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 788ms/step - accuracy: 0.5064 - loss: 2.2819
Epoch 55/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 780ms/step - accuracy: 0.5182 - loss: 2.2245
Epoch 56/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 837ms/step - accuracy: 0.5360 - loss: 2.1701
Epoch 57/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 786ms/step - accuracy: 0.5513 - loss: 2.1129
Epoch 58/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 780ms/step - accuracy: 0.5640 - loss: 2.0573
Epoch 59/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 777ms/step - accuracy: 0.5775 - loss: 2.0055
Epoch 60/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 769ms/step - accuracy: 0.5877 - loss: 1.9577
Epoch 61/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 768ms/step - accuracy: 0.6064 - loss: 1.9057
Epoch 62/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 769ms/step - accuracy: 0.6119 - loss: 1.8540
Epoch 63/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 778ms/step - accuracy: 0.6229 - loss: 1.8042
Epoch 64/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 805ms/step - accuracy: 0.6407 - loss: 1.7553
Epoch 65/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 780ms/step - accuracy: 0.6466 - loss: 1.7082
Epoch 66/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 780ms/step - accuracy: 0.6619 - loss: 1.6671
Epoch 67/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 771ms/step - accuracy: 0.6746 - loss: 1.6255
Epoch 68/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 835ms/step - accuracy: 0.6907 - loss: 1.5827
Epoch 69/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 797ms/step - accuracy: 0.6907 - loss: 1.5403
Epoch 70/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 789ms/step - accuracy: 0.7131 - loss: 1.4979
Epoch 71/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 775ms/step - accuracy: 0.7216 - loss: 1.4553
Epoch 72/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 787ms/step - accuracy: 0.7267 - loss: 1.4195
Epoch 73/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 779ms/step - accuracy: 0.7343 - loss: 1.3848
Epoch 74/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 829ms/step - accuracy: 0.7475 - loss: 1.3455
Epoch 75/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 780ms/step - accuracy: 0.7551 - loss: 1.3093
Epoch 76/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 773ms/step - accuracy: 0.7733 - loss: 1.2752
Epoch 77/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 848ms/step - accuracy: 0.7788 - loss: 1.2402
Epoch 78/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 770ms/step - accuracy: 0.7822 - loss: 1.2105
Epoch 79/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 774ms/step - accuracy: 0.7890 - loss: 1.1815
Epoch 80/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 780ms/step - accuracy: 0.7992 - loss: 1.1500
Epoch 81/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 21s 777ms/step - accuracy: 0.8068 - loss: 1.1188
Epoch 82/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 775ms/step - accuracy: 0.8136 - loss: 1.0921
Epoch 83/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 14s 717ms/step - accuracy: 0.8208 - loss: 1.0644
Epoch 84/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 14s 715ms/step - accuracy: 0.8258 - loss: 1.0347
Epoch 85/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 14s 715ms/step - accuracy: 0.8415 - loss: 1.0079
Epoch 86/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 21s 716ms/step - accuracy: 0.8449 - loss: 0.9819
Epoch 87/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 712ms/step - accuracy: 0.8521 - loss: 0.9551
Epoch 88/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 22s 786ms/step - accuracy: 0.8513 - loss: 0.9334
Epoch 89/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 796ms/step - accuracy: 0.8589 - loss: 0.9100
Epoch 90/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 16s 859ms/step - accuracy: 0.8674 - loss: 0.8856
Epoch 91/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 19s 801ms/step - accuracy: 0.8729 - loss: 0.8628
Epoch 92/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 21s 795ms/step - accuracy: 0.8746 - loss: 0.8398
Epoch 93/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 788ms/step - accuracy: 0.8826 - loss: 0.8190
Epoch 94/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 796ms/step - accuracy: 0.8852 - loss: 0.7989
Epoch 95/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 780ms/step - accuracy: 0.8941 - loss: 0.7780
Epoch 96/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 777ms/step - accuracy: 0.8924 - loss: 0.7608
Epoch 97/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 20s 762ms/step - accuracy: 0.8970 - loss: 0.7424
Epoch 98/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 767ms/step - accuracy: 0.9000 - loss: 0.7246
Epoch 99/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 14s 763ms/step - accuracy: 0.9076 - loss: 0.7067
Epoch 100/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 782ms/step - accuracy: 0.9131 - loss: 0.6894

In [319]:

sentences[45]

'“The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.”'

In [320]:
text = "The real lover"


reverse_word_index = {v: k for k, v in tokenizer.word_index.items()}

for i in range(20):
    token_text = tokenizer.texts_to_sequences([text])[0]
    padded_token_text = pad_sequences([token_text], maxlen=198, padding='pre')

    preds = model.predict(padded_token_text, verbose=0)[0]
    for word in text.lower().split():
        if word in tokenizer.word_index:
            idx = tokenizer.word_index[word]
            preds[idx] = preds[idx] * 0.01

    pos = np.argmax(preds)

    word = reverse_word_index.get(pos, "")
    text = text + " " + word
    print(text)

The real lover is
The real lover is a
The real lover is a man
The real lover is a man who
The real lover is a man who lives
The real lover is a man who lives fully
The real lover is a man who lives fully is
The real lover is a man who lives fully is prepared
The real lover is a man who lives fully is prepared to
The real lover is a man who lives fully is prepared to love
The real lover is a man who lives fully is prepared to love ”
The real lover is a man who lives fully is prepared to love ” you
The real lover is a man who lives fully is prepared to love ” you must
The real lover is a man who lives fully is prepared to love ” you must be
The real lover is a man who lives fully is prepared to love ” you must be intelligent
The real lover is a man who lives fully is prepared to love ” you must be intelligent read
The real lover is a man who lives fully is prepared to love ” you must be intelligent read them
The real lover is a man who lives fully is prepared to love ” you must be intelligent read them fairy
The real lover is a man who lives fully is prepared to love ” you must be intelligent read them fairy tales
The real lover is a man who lives fully is prepared to love ” you must be intelligent read them fairy tales if

In [279]:
model.input_shape

(None, 198)

In [280]:
padded_token_text.shape

(1, 198)